#!/bin/bash
echo Updating from GIT...
git pull
echo Installing Server Script...
sudo cp ./iSpindle.py /usr/local/bin/
echo Installing Sendmail Script...
sudo cp ./sendmail.py /usr/local/bin/
echo Done.
